a = int(input("Enter a number-1: "))
b = int(input("Enter b number-2: "))

print("a is greater than b: ", a > b)
print("a is less than b: ", a < b)
print("a is equal to b: ", a == b)
print("a is not equal to b: ", a != b)
print("a is greater than or equal to b: ", a >= b)
print("a is less than or equal to b: ", a <= b)
print("a is greater than b: ", a > b)
print("a is less than b: ", a < b)  