s = set()
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))
n = input("enter a number : ")
s.add(int(n))

print(s)